# AI Assistant Telegram Bot Configuration
# Этот файл содержит дефолтные настройки для бесплатного использования

spring:
  application:
    name: ai-assistant-telegram-bot
  
  main:
    banner-mode: console

# Основные настройки приложения
aiassistant:
  # Настройки Telegram Bot (ОБЯЗАТЕЛЬНО НАСТРОИТЬ!)
  telegram-bot-token: ${TELEGRAM_BOT_TOKEN:YOUR_BOT_TOKEN_HERE}
  telegram-bot-username: ${TELEGRAM_BOT_USERNAME:YOUR_BOT_USERNAME_HERE}
  
  # Настройки AI провайдера
  ai-provider:
    # Тип провайдера: groq, openai, ollama
    type: ${AI_PROVIDER_TYPE:groq}
    
    # API ключ (для Groq получить на: https://console.groq.com/keys)
    api-key: ${AI_API_KEY:YOUR_GROQ_API_KEY_HERE}
    
    # URL API (дефолт для Groq)
    api-url: ${AI_API_URL:https://api.groq.com/openai/v1/chat/completions}
    
    # Модель (бесплатные модели Groq)
    model: ${AI_MODEL:llama-3.1-8b-instant}
    
    # Максимальное количество токенов в ответе
    max-tokens: ${AI_MAX_TOKENS:1000}
    
    # Температура (креативность) 0.0-1.0
    temperature: ${AI_TEMPERATURE:0.7}
    
    # Таймаут запроса в миллисекундах
    timeout-ms: ${AI_TIMEOUT_MS:30000}
  
  # Поведение бота
  bot-behavior:
    # Максимальная длина сообщения от пользователя
    max-message-length: ${BOT_MAX_MESSAGE_LENGTH:4000}
    
    # Лимит запросов в минуту на пользователя
    rate-limit-per-minute: ${BOT_RATE_LIMIT:10}
    
    # Сообщения бота
    default-error-message: ${BOT_ERROR_MESSAGE:Извините, произошла ошибка при обработке вашего запроса. Попробуйте позже.}
    
    welcome-message: ${BOT_WELCOME_MESSAGE:Привет! 👋 Я AI-ассистент. Задайте мне любой вопрос, и я постараюсь помочь!}
    
    help-message: ${BOT_HELP_MESSAGE:🤖 AI-Ассистент\n\nКоманды:\n/start - Начать работу с ботом\n/help - Показать эту справку\n/status - Показать статус\n\nПросто отправьте мне сообщение, и я отвечу на ваш вопрос!}

# Настройки логирования
logging:
  level:
    com.aiassistant: DEBUG
    org.telegram: WARN
    okhttp3: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Дополнительные настройки Spring Boot
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
