# AI Assistant Telegram Bot Configuration
# Этот файл содержит настройки для приложения
# ВАЖНО: Замените значения YOUR_*_HERE на реальные ключи!

spring:
  application:
    name: ai-assistant-telegram-bot
  
  main:
    banner-mode: console

# Основные настройки приложения
aiassistant:
  # Настройки Telegram Bot (ОБЯЗАТЕЛЬНО НАСТРОИТЬ!)
  # Получить токен можно у @BotFather в Telegram
  telegram-bot-token: "YOUR_BOT_TOKEN_HERE"
  telegram-bot-username: "YOUR_BOT_USERNAME_HERE"
  
  # Настройки AI провайдера
  ai-provider:
    # Тип провайдера: groq, openai, ollama
    type: "groq"
    
    # API ключ (для Groq получить на: https://console.groq.com/keys)
    api-key: "YOUR_GROQ_API_KEY_HERE"
    
    # URL API (дефолт для Groq)
    api-url: "https://api.groq.com/openai/v1/chat/completions"
    
    # Модель (бесплатные модели Groq: llama-3.1-8b-instant, llama-3.1-70b-versatile, mixtral-8x7b-32768)
    model: "llama-3.1-8b-instant"
    
    # Максимальное количество токенов в ответе
    max-tokens: 1000
    
    # Температура (креативность) 0.0-1.0
    temperature: 0.7
    
    # Таймаут запроса в миллисекундах
    timeout-ms: 30000
  
  # Поведение бота
  bot-behavior:
    # Максимальная длина сообщения от пользователя
    max-message-length: 4000
    
    # Лимит запросов в минуту на пользователя
    rate-limit-per-minute: 10
    
    # Сообщения бота
    default-error-message: "Извините, произошла ошибка при обработке вашего запроса. Попробуйте позже."
    
    welcome-message: "Привет! 👋 Я AI-ассистент. Задайте мне любой вопрос, и я постараюсь помочь!"
    
    help-message: "🤖 AI-Ассистент\n\nКоманды:\n/start - Начать работу с ботом\n/help - Показать эту справку\n/status - Показать статус\n\nПросто отправьте мне сообщение, и я отвечу на ваш вопрос!"

# Настройки логирования
logging:
  level:
    com.aiassistant: DEBUG
    org.telegram: WARN
    okhttp3: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Дополнительные настройки Spring Boot
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
